# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='brief',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
