# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_platform', '0002_auto_20170314_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='活動名稱',
        ),
        migrations.RemoveField(
            model_name='post',
            name='brief',
        ),
        migrations.AddField(
            model_name='post',
            name='人數限制',
            field=models.TextField(default='人數限制'),
        ),
        migrations.AddField(
            model_name='post',
            name='地點',
            field=models.TextField(default='活動地點'),
        ),
        migrations.AddField(
            model_name='post',
            name='報名死線',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='對象',
            field=models.TextField(default='活動對象'),
        ),
        migrations.AddField(
            model_name='post',
            name='簡介',
            field=models.TextField(default='簡介你的活動'),
        ),
        migrations.AddField(
            model_name='post',
            name='結束日期與時間',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='聯絡資訊',
            field=models.TextField(default='例如活動專頁等'),
        ),
        migrations.AddField(
            model_name='post',
            name='費用',
            field=models.TextField(default='活動費用'),
        ),
        migrations.AddField(
            model_name='post',
            name='開始日期與時間',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
