# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_platform', '0003_auto_20170314_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='人數限制',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='地點',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='對象',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='費用',
            field=models.CharField(max_length=200),
        ),
    ]
