# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_platform', '0005_auto_20170314_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='圖片',
            field=models.TextField(default='image/.jpg'),
        ),
    ]
