# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_platform', '0010_auto_20170323_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='副標題',
            field=models.CharField(default='建議最多二十五字', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='活動名稱',
            field=models.CharField(default='建議最多十四字', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='簡介',
            field=models.TextField(default='簡介你的活動(建議最多三百字)', max_length=300),
        ),
    ]
