# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_platform', '0015_auto_20170323_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='人數限制',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='對象',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='詳細地點',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='詳細費用',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
