# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_platform', '0016_auto_20170325_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20)),
                ('restaurant', models.ManyToManyField(to='activity_platform.Post')),
            ],
        ),
    ]
