# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_platform', '0017_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='restaurant',
            new_name='post',
        ),
    ]
