# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_platform', '0018_auto_20170411_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='人數限制',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='圖片',
            field=models.ImageField(default='back.png', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='地點',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='對象',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='簡介',
            field=models.TextField(default='簡介你的活動(建議最多三百二十五字)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='結束日期與時間',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='費用',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
